language: rust
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cargo install --force --git https://github.com/cobalt-org/cobalt.rs.git
  - cask
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
script:
  - emacs --version
  - make test

notifications:
  email: false
